export const TICKET_ITEM_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELED: 'CANCELED',
};

export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ANALYST: 'ANALYST',
  AUDITOR: 'AUDITOR',
};

export const AUDIT_STATUS = {
  OPEN: 'OPEN',
  DONE: 'DONE',
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN PROGRESS',
  CANCELED: 'CANCELED',
  REVIEW: 'REVIEW',
};
